export const SHOW_SEARCH_RESULTS = "SHOW_SEARCH_RESULTS"

export const SORT_ALPHABETS_ASC = "SORT_ALPHABETS_ASC"
export const SORT_ALPHABETS_DESC = "SORT_ALPHABETS_DESC"

export const SORT_BY_DATE_ASC = "SORT_BY_DATE_ASC"
export const SORT_BY_DATE_DESC = "SORT_BY_DATE_DESC"

export const SORT_BY_QUALITY_ASC = "SORT_BY_QUALITY_ASC"
export const SORT_BY_QUALITY_DESC = "SORT_BY_QUALITY_DESC"

//filter-explicit

export const FILTER_EXPLICIT = "FILTER_EXPLICIT"